name: bob-ci-35
channels:
- https://www.idiap.ch/software/bob/conda/
- defaults
dependencies:
- sphinx==1.3.5
- Pygments==2.1.1
- docutils==0.12
- mock
- pillow==3.0.0
- sphinx_rtd_theme==0.1.7
- alabaster>=0.7,<0.8,!=0.7.5
- bob
