name: bob-ci-35
channels:
- https://www.idiap.ch/software/bob/conda/
- defaults
dependencies:
- sphinx==1.3.5
- Pygments==2.1.1
- docutils==0.12
- mock
- pillow==3.0.0
- sphinx_rtd_theme==0.1.7
- alabaster>=0.7,<0.8,!=0.7.5
- bob.extension
- bob.blitz
- bob.core
- bob.io.base
- bob.sp
- bob.ap
- bob.math
- bob.measure
- bob.db.base
- bob.io.audio
- bob.io.image
- bob.io.video
- bob.io.matlab
- bob.ip.base
- bob.ip.color
- bob.ip.draw
- bob.ip.gabor
- bob.learn.activation
- bob.learn.libsvm
- bob.learn.linear
- bob.learn.mlp
- bob.learn.em
- bob.learn.boosting
- bob.db.iris
- bob.db.wine
- bob.db.mnist
- bob.db.atnt
- bob.ip.facedetect
- bob.ip.optflow.hornschunck
- bob.ip.optflow.liu
- bob.ip.flandmark
