name: bob-ci-35
channels:
- conda-forge
- defaults
dependencies:
- alabaster
- babel
- backports
- bokeh
- cairo
- chest
- cloudpickle
- cmake
- blas
- boost
- ffmpeg
- giflib
- icu
- ipdb
- libblitz
- libmatio
- libsvm
- numpy
- openblas
- scikit-learn
- scipy
- sox
- vlfeat
- x264
- coverage
- cycler
- cython
- dask
- decorator
- docopt
- docutils
- fontconfig
- freetype
- get_terminal_size
- glib
- harfbuzz
- hdf5
- heapdict
- imagesize
- ipython
- ipython_genutils
- jbig
- jinja2
- jpeg
- libffi
- libgfortran
- libpng
- libtiff
- libxml2
- locket
- markupsafe
- matplotlib
- networkx
- nomkl
- nose
- numexpr
- openssl
- pandas
- pango
- partd
- path.py
- pexpect
- pickleshare
- pillow
- pip
- pixman
- pkg-config
- psutil
- ptyprocess
- pygments
- pyparsing
- pyqt
- python
- python-dateutil
- pytz
- pyyaml
- qt
- readline
- requests
- scikit-image
- setuptools
- simplegeneric
- sip
- six
- snowballstemmer
- sphinx
- sphinx_rtd_theme
- sqlalchemy
- sqlite
- tk
- toolz
- tornado
- traitlets
- wheel
- xz
- yaml
- zlib
